baseURL = 'http://mggg.cloud/'
languageCode = 'en-us'
title = "Jiamin's Blog"
theme = 'ananke'
[params]
author = "Jiamin"
favicon= "img/favicon.ico"
background_color_class=""

[sitemap]
  changefreq = "daily"  # Sitemap 中页面的更改频率
  priority = 0.5  # Sitemap 中页面的优先级


[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/wangjm10"