baseURL = 'https://mggg.cloud/'
title = "mggg's Blog"

theme = 'ananke'
[params]
author = "mggg"
description = "mggg is the ID I use when playing Dota. Currently, I am very interested in AI, and this is my blog, so I called mggg's blog"
favicon= "img/favicon.ico"
background_color_class=""
github="https://github.com/mggger"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


[sitemap]
  changefreq = "daily"  # Sitemap 中页面的更改频率
  priority = 0.5  # Sitemap 中页面的优先级


[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/wangjm10"

[[menu.main]]
  name = "Links"
  url = "/friends"
  weight = 5

[[menu.main]]
  name = "English"
  url = "/en/"
  weight = 3

[[menu.main]]
  name = "中文"
  url = "/zh/"
  weight = 4


[[menu.main]]
  name = "GPTs"
  url = "https://gptdevelopment.online/"
  weight = 0
