baseURL = 'https://mggg.cloud/'
title = "mggg's Blog"
theme = 'ananke'
[params]
author = "mggg"
favicon= "img/favicon.ico"
background_color_class=""
github="https://github.com/mggger"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


[sitemap]
  changefreq = "daily"  # Sitemap 中页面的更改频率
  priority = 0.5  # Sitemap 中页面的优先级


[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/wangjm10"

[[menu.main]]
identifier = "aboutme"
name = "About Me"
url = "/en/about-me/"
weight = 2

[[menu.main]]
  name = "Links"
  url = "/friends"
  weight = 5

[[menu.main]]
  name = "English"
  url = "/en/"
  weight = 3

[[menu.main]]
  name = "中文"
  url = "/zh/"
  weight = 4

[[menu.main]]
  name = "Try Free AI"
  url = "https://freechat.mggg.cloud/"
  weight = 1

[[menu.main]]
  name = "GPTs"
  url = "https://gpts.mggg.cloud/"
  weight = 0