baseURL = 'http://mggg.cloud/'
languageCode = 'en-us'
title = 'Nomadic Numbers'
theme = 'ananke'
[params]
  author = "GptWang"
  favicon= "img/favicon.ico"

[sitemap]
  changefreq = "daily"  # Sitemap 中页面的更改频率
  priority = 0.5  # Sitemap 中页面的优先级
